env:
  CIRRUS_VAULT_URL: https://vault.sonar.build:8200
  CIRRUS_VAULT_AUTH_PATH: jwt-cirrusci
  CIRRUS_VAULT_ROLE: cirrusci-${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}

  SONAR_TOKEN: VAULT[development/kv/data/sonarcloud data.token]
  ARTIFACTORY_URL: https://repox.jfrog.io/
  ARTIFACTORY_DEPLOY_ACCESS_TOKEN: VAULT[development/artifactory/token/${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-qa-deployer access_token]
  ARTIFACTORY_PROMOTE_ACCESS_TOKEN: VAULT[development/artifactory/token/${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-promoter access_token]
  # Use bash (instead of sh on linux or cmd.exe on windows)
  CIRRUS_SHELL: bash

only_sonarsource_qa: &ONLY_SONARSOURCE_QA
  only_if: $CIRRUS_USER_COLLABORATOR == 'true' && $CIRRUS_TAG == "" && ($CIRRUS_PR != "" || $CIRRUS_BRANCH == "master" || $CIRRUS_BRANCH =~ "branch-.*" || $CIRRUS_BRANCH =~ "dogfood-on-.*")

container_definition: &CONTAINER_DEFINITION
  dockerfile: .cirrus/nodejs.Dockerfile
  cluster_name: ${CIRRUS_CLUSTER_NAME}
  builder_role: cirrus-builder
  builder_image: docker-builder-v*
  builder_instance_type: t3.small
  builder_subnet_id: ${CIRRUS_AWS_SUBNET}
  region: eu-central-1
  namespace: default
  use_in_memory_disk: true

build_task:
  <<: *ONLY_SONARSOURCE_QA
  eks_container:
    <<: *CONTAINER_DEFINITION
    docker_arguments:
      CIRRUS_AWS_ACCOUNT: ${CIRRUS_AWS_ACCOUNT}
    cpu: 3
    memory: 8G
  env:
    SONARSOURCE_QA: true
  node_version_script:
    - node --version
  script:
    - if [ -n "${CIRRUS_BASE_BRANCH}" ]; then git fetch origin "${CIRRUS_BASE_BRANCH}"; fi
    - jfrog config add repox --url $ARTIFACTORY_URL --access-token $ARTIFACTORY_DEPLOY_ACCESS_TOKEN
    - jfrog npm-config --repo-resolve npm --repo-deploy sonarsource-npm-public-qa
    - jfrog rt npm-ci
    - npm run check-format
    - npm run build
    - ./scripts/test-ci.sh
    - ./scripts/analyze_and_publish.sh

qa_task:
  depends_on:
    - build
  eks_container:
    matrix:
      - docker_arguments:
          NODE_VERSION: 16
          CIRRUS_AWS_ACCOUNT: ${CIRRUS_AWS_ACCOUNT}
      - docker_arguments:
          NODE_VERSION: 18
          CIRRUS_AWS_ACCOUNT: ${CIRRUS_AWS_ACCOUNT}
      - docker_arguments:
          NODE_VERSION: 20
          CIRRUS_AWS_ACCOUNT: ${CIRRUS_AWS_ACCOUNT}
    <<: *CONTAINER_DEFINITION
    cpu: 3
    memory: 8G
  env:
    SONARSOURCE_QA: true
  node_version_script:
    - node --version
  script:
    - jfrog config add repox --url $ARTIFACTORY_URL --access-token $ARTIFACTORY_DEPLOY_ACCESS_TOKEN
    - jfrog npm-config --repo-resolve npm --repo-deploy sonarsource-npm-public-qa
    - git submodule update --init --depth 1 -r
    - jfrog rt npm-ci
    - npm run build
    - npm run ruling

ws_scan_task:
  depends_on:
    - build
  eks_container:
    <<: *CONTAINER_DEFINITION
    docker_arguments:
      CIRRUS_AWS_ACCOUNT: ${CIRRUS_AWS_ACCOUNT}
    cpu: 2
    memory: 2G
  # run only on master and long-term branches
  only_if: $CIRRUS_USER_COLLABORATOR == 'true' && ($CIRRUS_BRANCH == "master" || $CIRRUS_BRANCH =~ "branch-.*")
  env:
    WS_APIKEY: VAULT[development/kv/data/mend data.apikey]
  maven_cache:
    folder: ${CIRRUS_WORKING_DIR}/.m2/repository
  whitesource_script:
    - ./scripts/run_ws_scan.sh
  allow_failures: 'true'
  always:
    ws_artifacts:
      path: 'whitesource/**/*'
