gcp_credentials: ENCRYPTED[!17c59813193e86cc337bce848b358412b90f50bc5fe1b8b39d363cdf14a41ebe76cfba0482e7f81d076994b9f6dbfb4c!]

env:
  GITHUB_TOKEN: ENCRYPTED[!f272985ea5b49b3cf9c414b98de6a8e9096be47bfcee52f33311ba3131a2af637c1b956f49585b7757dd84b7c030233a!]
  SONAR_TOKEN: ENCRYPTED[!4e5894b7b32f763db69e70fb56188d3f42539db36374b1f97c425f37a7ecd441c28a9da267c461b9cc8fb53124f14c22!]
  REPOX_CLI_CONFIG_QA_DEPLOYER: ENCRYPTED[!5aec4f862abfef35be645c235bbe93c72642ddbf9734b27dabdfe4e3a2d800b32d6e3474e2a11546ddd18dc076391b01!]
  REPOX_CLI_CONFIG_BUILD_PROMOTER: ENCRYPTED[!e4f8d6e32933306ee4d11f1e04bb9cc3c88fa45e53f1252342279da960fa5ae01c55e3f144a55ba8245ae3bab5b08c64!]
  # Use bash (instead of sh on linux or cmd.exe on windows)
  CIRRUS_SHELL: bash

only_sonarsource_qa: &ONLY_SONARSOURCE_QA
  only_if: $CIRRUS_USER_COLLABORATOR == 'true' && ($CIRRUS_PR != "" || $CIRRUS_BRANCH == "master" || $CIRRUS_BRANCH =~ "branch-.*" || $CIRRUS_BRANCH =~ "dogfood-on-.*")

container_definition: &CONTAINER_DEFINITION
  builder_image_project: language-team
  builder_image_name: docker-builder-lt-v1
  cluster_name: cirrus-ci-lt-cluster
  zone: us-central1-a
  namespace: default
  use_in_memory_disk: true

build_task:
  <<: *ONLY_SONARSOURCE_QA
  gke_container:
    matrix:
      - dockerfile: .cirrus/nodejs-10.Dockerfile
      - dockerfile: .cirrus/nodejs-12.Dockerfile
      - dockerfile: .cirrus/nodejs-14.Dockerfile
      - dockerfile: .cirrus/nodejs-15.Dockerfile
    <<: *CONTAINER_DEFINITION
    cpu: 3
    memory: 8G
  env:
    CIRRUS_CLONE_DEPTH: 10
    SONARSOURCE_QA: true
  script:
    - jfrog config import $REPOX_CLI_CONFIG_QA_DEPLOYER
    - jfrog rt npm-config --repo-resolve npm --repo-deploy sonarsource-npm-public-qa
    - init_git_submodules -r
    - jfrog rt npm-ci
    - npm run typecheck
    - npm run build
    - ./scripts/test-ci.sh
    - npm run check-format
    - npm run lint
    - npm run ruling
    - ./scripts/analyze_and_publish.sh

ws_scan_task:
  depends_on:
    - build
  gke_container:
    dockerfile: .cirrus/nodejs-12.Dockerfile
    <<: *CONTAINER_DEFINITION
    cpu: 2
    memory: 2G
  # run only on master and long-term branches
  only_if: $CIRRUS_USER_COLLABORATOR == 'true' && ($CIRRUS_BRANCH == "master" || $CIRRUS_BRANCH =~ "branch-.*")
  env:
    WS_APIKEY: ENCRYPTED[!3929c6148b9dfc751a2d17c590b15d755f82cd9c108f2de5f24a5b32f2a0c26144e921fab7e2c959fc2824d6d6d1550d!]
  maven_cache:
    folder: ${CIRRUS_WORKING_DIR}/.m2/repository
  whitesource_script:
    - ./scripts/run_ws_scan.sh
  allow_failures: "true"
  always:
    ws_artifacts:
      path: "whitesource/**/*"
