gcp_credentials: ENCRYPTED[!17c59813193e86cc337bce848b358412b90f50bc5fe1b8b39d363cdf14a41ebe76cfba0482e7f81d076994b9f6dbfb4c!]

env:
  GITHUB_TOKEN: ENCRYPTED[!f272985ea5b49b3cf9c414b98de6a8e9096be47bfcee52f33311ba3131a2af637c1b956f49585b7757dd84b7c030233a!]
  SONAR_TOKEN: ENCRYPTED[!4e5894b7b32f763db69e70fb56188d3f42539db36374b1f97c425f37a7ecd441c28a9da267c461b9cc8fb53124f14c22!]
  NPM_DEPLOYER_AUTH: ENCRYPTED[!f4021c529fe14ea134a81e2a147782f095a68c3805328c09409e06e229f66e7fbe742e1b3c522a0cdc2187e730de3814!]
  # Use bash (instead of sh on linux or cmd.exe on windows)
  CIRRUS_SHELL: bash

only_sonarsource_qa: &ONLY_SONARSOURCE_QA
  only_if: $CIRRUS_USER_COLLABORATOR == 'true' && ($CIRRUS_PR != "" || $CIRRUS_BRANCH == "master" || $CIRRUS_BRANCH =~ "branch-.*" || $CIRRUS_BRANCH =~ "dogfood-on-.*")

container_definition: &CONTAINER_DEFINITION
  builder_image_project: language-team
  builder_image_name: docker-builder-lt-v1
  cluster_name: cirrus-ci-lt-cluster
  zone: us-central1-a
  namespace: default
  use_in_memory_disk: true

plugin_qa_task:
  <<: *ONLY_SONARSOURCE_QA
  gke_container:
    matrix:
      - dockerfile: .cirrus/nodejs-10.Dockerfile
      - dockerfile: .cirrus/nodejs-12.Dockerfile
      - dockerfile: .cirrus/nodejs-14.Dockerfile
      - dockerfile: .cirrus/nodejs-15.Dockerfile
    <<: *CONTAINER_DEFINITION
    cpu: 3
    memory: 8G
  env:
    CIRRUS_CLONE_DEPTH: 10
    SONARSOURCE_QA: true
  npmrc_file:
    path: ${HOME}/.npmrc
    variable_name: NPM_DEPLOYER_AUTH
  script:
    - init_git_submodules -r
    - yarn
    - yarn typecheck
    - yarn build
    - ./scripts/test-ci.sh
    - yarn prettier --list-different "{src,tests}/**/*.{js,ts}"
    - yarn lint
    - yarn ruling
    - ./scripts/analyze_and_publish.sh
